### ISSUE TITLE
Improve modal focus behaviour

### ISSUE THREAD

**Issue by CarloPalinckx** [MyOnlineStore/bricks#423]
### Is your feature request related to a problem? Please describe ⚡️
When opening a modal, it gets a very low tab priority. This means that when you open it and want to tab through it, you have to go through the entire page first.

### Describe the solution you'd like ✨
The best solution would be to trigger a focus on the modal container when the open prop is changed.

### Describe alternatives you've considered 🎡
Alternatively we could set the focus to the button group instantly. Which doesn't cover all cases because there could be focusable content in the modal as well. This would require a prop to set the focus behaviour.

### Additional context 🖼

Watch me having to tab through all the rows in this example ⬇️ 
![Aug-12-2019 10-06-17](https://user-images.githubusercontent.com/6347900/62852169-ef049400-bce8-11e9-89c3-b49385750923.gif)

**Comment by woutsluiter** [comment]
I don't think focusing on the primary button is necessarily a bad thing. It provides a nice fast flow when you can confirm (Enter) of cancel (Escape) right away. You could always Tab in the other direction when the content has focus-able elements. Maybe you can focus on the button group if present, otherwise the modal itself?

**Comment by hborghols** [comment]
If the modal contains a form (as it does in a lot of places where we apply it) you wouldn't want to always have to reverse-tab to get to the form. I think the solution most pleasant to work with for both devs and users would be to pick a default (imo this could be the buttongroup) to focus on with an optional prop to change this behavior.

**Comment by Dreamdealer** [comment]
Can't we automatically focus the first element in the modal's content if any, and otherwise focus on the primary button, or manually set the first element to focus with a prop? With that solution one has the advantage of the fast flow (like Wout says) and the flexibility without adding to much workload to devs (as Henk suggests).

**Comment by woutsluiter** [comment]
>If the modal contains a form (as it does in a lot of places where we apply it) you wouldn't want to always have to reverse-tab to get to the form.
Hmm true. I like the idea of defaulting on the primary button unless told otherwise.

**Comment by woutsluiter** [comment]
> automatically focus the first element in the modal's content if any, and otherwise focus on the primary button

Good option as well. And as fallback when neither of those are present focus on the modal itself.
