### ISSUE TITLE
Additional icon set

### ISSUE THREAD

**Issue by CarloPalinckx** [MyOnlineStore/bricks#96]
We currently support 2 icon sets with the `Icon` component. "small" and "large" (18x18 and 60x60 respectively). We would like to add a third one which has a canvas of 12x12. The props need to be expanded to support this third set as well.

`small | large` could become `small | medium | large`.

The svg files are inline with a webpack loader and can be imported. (we import them with require() in `https://github.com/MyOnlineStore/bricks/blob/master/src/components/Icon/types.ts` for convenience because it gives you instant assignment)

**Comment by hborghols** [comment]
The props have been expanded to support a medium set on branch "additional-icon-set". However, we ran into the problem that part of the icons is stroke based instead of fill based. The stroke based icons are displayed incorrectly because they are filled.

The fix is to convert the affected icons to fill based. As soon as this is done, the new icons can be imported and the issue can be closed.
